# This is a basic workflow to help you get started with Actions

name: My first action
on: [push, workflow_dispatch]
jobs:
 order_oneline:
   runs-on: self-hosted
   steps:
   - name: open mobile
     run: echo mobile opened 
   - name: make payment
     run: echo " I made a payment of 500rs"
 eat_food:
  runs-on: ubuntu-latest
  needs: order_oneline
  steps:
  - name: open mouth
    run: echo "opened mouth"
  - name : eat food
    run: echo " I am eating food"
    

