# This is a basic workflow to help you get started with Actions

name: My first action
on: [push, workflow_dispatch]
jobs:
 order_oneline:
   runs-on: ubuntu-latest
   steps:
   - name: open mobile
     run: echo mobile opened 
   - name: make payment
     run: echo " I made a payment of 500rs"
    

